RISC-V: Remove math.h import to resolve missing stubs failures
Resolves some of the missing stubs failures:
fatal error: gnu/stubs-lp64d.h: No such file or directory
compilation terminated.

2023-09-20 Juzhe Zhong <juzhe.zhong@rivai.ai>

gcc/testsuite/ChangeLog:

	* gcc.target/riscv/rvv/autovec/vls/def.h: Remove unneeded math.h
	import.

Tested-by: Patrick O'Neill <patrick@rivosinc.com>